basePath: /api/v1
definitions:
  types.FailureErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
  types.FailureResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  types.GetMeResponse:
    properties:
      email:
        type: string
      id:
        type: string
    type: object
info:
  contact: {}
  description: This is an API of payment-service for Socialweb application
  title: go-servise-entoty Swagger
  version: "1.0"
paths:
  /entity/create:
    post:
      consumes:
      - application/json
      description: Test endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.GetMeResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.FailureErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: CreateEntity info
      tags:
      - info
  /entity/user_info:
    get:
      consumes:
      - application/json
      description: Test endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.GetMeResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.FailureErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get user info
      tags:
      - info
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
